apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
# https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types