apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ivorlun/bitnami-nginx-80:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args: ["-nginx.scrape-uri=http://nginx-clusterip/stub_status"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9113
