repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.4.0

- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.10.1
  set:
  - name: installCRDs
    value: true

- name: cert-manager-cluster-issuer
  chart: ./issuer-cr

- name: harbor
  namespace: harbor
  chart: harbor/harbor
  version: 1.10.2
  values:
  - "../harbor/values.yaml"

helmDefaults:
  wait: true
  waitForJobs: true
  createNamespace: true
