# https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
iamge:
  tag: 1.9.10-debug
logLevel: trace

rbac:
  nodeAccess: true

config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Retry_Limit False
        Time_Key time
        Trace_Error On

    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Time_Key time
        Trace_Error On
