# https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch
image:
  tag: "1.9.10-debug"
# backend:
#   type: es
#   es:
#     host: elasticsearch-master
logLevel: debug
config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-master
        Logstash_Format On
        Retry_Limit False
        Write_Operation: index
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Write_Operation: index
