controller:

  config:
    log-format-escape-json: "true"
    log-format-upstream: '{"timestamp": "$time_iso8601", "proxy_protocol_addr": "$proxy_protocol_addr",
      "remote_addr": "$remote_addr", "remote_user": "$remote_user", "time_local": "$time_local",
      "request": "$request", "status": "$status", "body_bytes_sent": "$body_bytes_sent",
      "http_referer": "$http_referer", "http_user_agent": "$http_user_agent",
      "request_length": "$request_length", "request_time": "$request_time",
      "proxy_upstream_name": "$proxy_upstream_name",
      "proxy_alternative_upstream_name": "$proxy_alternative_upstream_name",
      "upstream_addr": "$upstream_addr", "upstream_response_length": "$upstream_response_length",
      "upstream_response_time": "$upstream_response_time", "upstream_status": "$upstream_status",
      "req_id": "$req_id", "server_protocol":"$server_protocol", "host": "$host", "uri": "$uri",
      "args": "$args", "x-forward-for": "$proxy_add_x_forwarded_for"}'

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
